sudo: required

git:
  depth: 1

language: node_js

node_js:
  - "9"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
  - npm cache clean --force
  - rm -rf node_modules/

install:
  - npm run setup --debug

script:
  - npm run doc
  - npm run test
