theme: "readthedocs"

docs_dir: ./website
site_dir: ./packages/strapi-generate-new/files/public
theme_dir: ./website/theme

site_name: "Strapi"
site_description: "Node.js framework powering API-driven web and mobile applications."
site_author: "Strapi"
site_url: "http://strapi.io/"

repo_name: "Strapi"
repo_url: "https://github.com/strapi/strapi"

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - toc:
      permalink: "#"

extra:
  command: "$ npm install strapi-cli -g"
  baseline: "Powering API-driven web and mobile applications."
  start: "Get started"
  current_version: "Current version"
  version: "2.0.0"

pages:
  - Home: ./index.md
  - Prologue:
    - Introduction: ./documentation/prologue/why.md
    - Install Strapi: ./documentation/prologue/installation.md
    - How it works: ./documentation/prologue/start.md
  - Architecture foundations:
    - Configuration: ./documentation/architecture/configuration.md
    - Router: ./documentation/architecture/router.md
    - Context: ./documentation/architecture/context.md
    - Request: ./documentation/architecture/request.md
    - Response: ./documentation/architecture/response.md
    - Databases: ./documentation/architecture/databases.md
    - Views: ./documentation/architecture/views.md
    - Logging: ./documentation/architecture/logging.md
  - Concepts:
    - Authentication: ./documentation/concepts/authentication.md
    - GraphQL: ./documentation/concepts/graphql.md
    - JSON API: ./documentation/concepts/jsonapi.md
    - WebSockets: ./documentation/concepts/websockets.md
    - Internationalization: ./documentation/concepts/internationalization.md
    - Scheduled tasks: ./documentation/concepts/cron.md
    - Services: ./documentation/concepts/services.md
    - Policies: ./documentation/concepts/policies.md
    - Sessions: ./documentation/concepts/sessions.md
  - SQL databases:
    - Models: ./documentation/sql/models.md
    - Migrations: ./documentation/sql/migrations.md
    - Query builder: ./documentation/sql/queries.md
    - Raw: ./documentation/sql/raw.md
    - Interfaces: ./documentation/sql/interfaces.md
    - SQL ORM: ./documentation/sql/orm.md
  - Advanced usage:
    - Security: ./documentation/advanced/security.md
    - Lifecycle events: ./documentation/advanced/events.md
    - Error handling: ./documentation/advanced/errors.md
    - Custom generators: ./documentation/advanced/generators.md
    - Custom hooks: ./documentation/advanced/hooks.md
  - Legal Info:
    - Governance: ./info/governance.md
    - Code Of Conduct: ./info/conduct.md
    - Releases: ./info/releases.md
    - Security: ./info/security.md
    - Trademarks: ./info/trademarks.md
    - Licenses: ./info/licenses.md
    - Support: ./info/support.md
